import type { AnnotationMark } from './types';

export const ANNOTATION_MARKS: AnnotationMark[] = [
  { category: '单元', label: '语调单元', symbol: '\n', description: '换行，表示一个语调单元' },
  { category: '单元', label: '截断语调单元', symbol: '--', description: '置于被截断的语调单元处' },
  { category: '单元', label: '截断词', symbol: '-', description: '置于被截断的词处' },
  { category: '说话者', label: '说话者/话轮起始', symbol: ': ', description: '置于说话者名字后' },
  { category: '说话者', label: '话语重叠', symbol: '[  ]', description: '重叠内容置于方括号中', cursorOffset: 2 },
  { category: '末尾音高', label: '降', symbol: '\\', description: '置于语调单元末尾' },
  { category: '末尾音高', label: '升', symbol: '/', description: '置于语调单元末尾' },
  { category: '末尾音高', label: '平', symbol: '_', description: '置于语调单元末尾' },
  { category: '韵律重音和延长', label: '主韵律重音', symbol: '^', description: '置于重音音节前' },
  { category: '韵律重音和延长', label: '次韵律重音', symbol: '‘', description: '置于重音音节前' },
  { category: '韵律重音和延长', label: '加强', symbol: '!', description: '置于目标音节前' },
  { category: '韵律重音和延长', label: '延长', symbol: '=', description: '置于目标音节后' },
  { category: '音节调型', label: '降', symbol: '\\', description: '置于目标音节前' },
  { category: '音节调型', label: '升', symbol: '/', description: '置于目标音节前' },
  { category: '音节调型', label: '降升', symbol: '\\/', description: '置于目标音节前' },
  { category: '音节调型', label: '升降', symbol: '/\\', description: '置于目标音节前' },
  { category: '音节调型', label: '平', symbol: '_', description: '置于目标音节前' },
  { category: '停顿', label: '长停顿', symbol: '...(N)', description: '括号内标示秒数', cursorOffset: 4 },
  { category: '停顿', label: '中停顿', symbol: '...', description: '中等停顿' },
  { category: '停顿', label: '短停顿', symbol: '..', description: '短停顿' },
  { category: '停顿', label: '无缝接轨', symbol: '(0)', description: '置于后一个语调单元开头' },
  { category: '声带噪声', label: '声带噪声', symbol: '( )', description: '括号中用全大写标示', cursorOffset: 1 },
  { category: '声带噪声', label: '吸气', symbol: '(H)', description: '吸气' },
  { category: '声带噪声', label: '吐气', symbol: '(Hx)', description: '吐气' },
  { category: '声带噪声', label: '喉塞音', symbol: '%', description: '喉塞音' },
  { category: '声带噪声', label: '笑声', symbol: '@', description: '一声一个 @' },
  { category: '声带噪声', label: '啧', symbol: '(TSK)', description: '啧声' },
  { category: '语音标记', label: '语音/音位转写', symbol: '(/  /)', description: '国际音标置于斜线中间', cursorOffset: 3 },
  { category: '转写员视角', label: '研究者备注', symbol: '((  ))', description: '备注置于双括号里', cursorOffset: 3 },
  { category: '转写员视角', label: '听不清内容', symbol: '<X  X>', description: '猜测内容置于 X 之间', cursorOffset: 3 },
  { category: '转写员视角', label: '无法辨识音节', symbol: 'X', description: '一个 X 代表一个音节' },
  { category: '特殊标记', label: '时长', symbol: '(N)', description: '括号内标示秒数', cursorOffset: 1 },
  { category: '特殊标记', label: '被隔开的 IU', symbol: '&', description: '置于前半 IU 末尾和后半 IU 开头' },
  { category: '特殊标记', label: '内嵌 IU', symbol: '<|  |>', description: 'IU 内容置于 | 之间', cursorOffset: 3 },
  { category: '特殊标记', label: '语码转换', symbol: '<L2  L2>', description: '内容置于 L2 之间', cursorOffset: 4 },
  { category: '非转写行', label: '非转写行', symbol: '$', description: '置于每行开头' },
  { category: '非转写行', label: '逐行注释行', symbol: '$G', description: '置于每行开头' },
  { category: '音质', label: '音质', symbol: '<Y  Y>', description: 'Y 表示音质缩写，内容置于之间', cursorOffset: 3 },
  { category: '音质', label: '笑着说', symbol: '<@  @>', description: '笑着说的音质', cursorOffset: 3 },
  { category: '音质', label: '引述', symbol: '<Q  Q>', description: '引述的音质', cursorOffset: 3 },
  { category: '音量大小', label: '强/大声', symbol: '<F  F>', description: '大声', cursorOffset: 3 },
  { category: '音量大小', label: '弱/小声', symbol: '<P  P>', description: '小声', cursorOffset: 3 },
  { category: '音量大小', label: '渐强', symbol: '<CR  CR>', description: '逐渐变大声', cursorOffset: 4 },
  { category: '音量大小', label: '渐弱', symbol: '<DIM  DIM>', description: '逐渐变小声', cursorOffset: 5 },
  { category: '音高', label: '较高音高', symbol: '<HI  HI>', description: '较高音高', cursorOffset: 4 },
  { category: '音高', label: '较低音高', symbol: '<LO  LO>', description: '较低音高', cursorOffset: 4 },
  { category: '音高', label: '音域加宽', symbol: '<W  W>', description: '音域加宽', cursorOffset: 3 },
  { category: '音高', label: '音域收窄', symbol: '<N  N>', description: '音域收窄', cursorOffset: 3 },
  { category: '音高', label: '插话式韵律', symbol: '<PAR  PAR>', description: '插话式韵律', cursorOffset: 5 },
  { category: '速度与节奏', label: '快板', symbol: '<A  A>', description: '语速快', cursorOffset: 3 },
  { category: '速度与节奏', label: '慢板', symbol: '<L  L>', description: '语速慢', cursorOffset: 3 },
  { category: '速度与节奏', label: '有节奏', symbol: '<RH  RH>', description: '有节奏性', cursorOffset: 4 },
  { category: '速度与节奏', label: '逐词加强', symbol: '<MRC  MRC>', description: '每个词突出加强', cursorOffset: 5 },
  { category: '速度与节奏', label: '无节奏/中止', symbol: '<ARH  ARH>', description: '无节奏或话语即将中止', cursorOffset: 5 },
  { category: '声音音质', label: '耳语', symbol: '<WH  WH>', description: '耳语', cursorOffset: 4 },
  { category: '声音音质', label: '气嗓音', symbol: '<BR  BR>', description: '气嗓音', cursorOffset: 4 },
  { category: '声音音质', label: '沙哑', symbol: '<HSK  HSK>', description: '沙哑', cursorOffset: 5 },
  { category: '声音音质', label: '挤喉音', symbol: '<CRK  CRK>', description: '挤喉音', cursorOffset: 5 },
  { category: '声音音质', label: '假音', symbol: '<FAL  FAL>', description: '假音', cursorOffset: 5 },
  { category: '声音音质', label: '颤抖', symbol: '<TRM  TRM>', description: '颤抖', cursorOffset: 5 },
  { category: '声音音质', label: '啜泣', symbol: '<SOB  SOB>', description: '啜泣', cursorOffset: 5 },
  { category: '声音音质', label: '哭', symbol: '<CRY  CRY>', description: '哭', cursorOffset: 5 },
  { category: '声音音质', label: '打呵欠', symbol: '<YWN  YWN>', description: '打呵欠', cursorOffset: 5 },
  { category: '声音音质', label: '叹息', symbol: '<SGH  SGH>', description: '叹息', cursorOffset: 5 },
];
